// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanningWebAgit.Models;

#nullable disable

namespace PlanningWebAgit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PlanningWebAgit.Models.RencanaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JumatAsli")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JumatHasil")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KamisAsli")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KamisHasil")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MingguAsli")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MingguHasil")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RabuAsli")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RabuHasil")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SabtuAsli")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SabtuHasil")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelasaAsli")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelasaHasil")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeninAsli")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeninHasil")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TanggalProduksi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RencanaModel");
                });
#pragma warning restore 612, 618
        }
    }
}
